- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution in ["Ubuntu", "Debian", "Linux Mint"]

  tasks:
    - include: tasks/packages.yml

  roles:
    - themes
    - applets
    - panels    
    - desktop
    - config
