  # desktop icon size is store in /home/user/.config/nemo/desktop-metadata
  # line : nemo-icon-view-zoom-level=2
  # 1. Smaller 2. Small 3. Normal 4. Large 5. Larger
- name: change desktop icon size to samll
  become_user: "{{user}}"
  lineinfile:
    path: /home/{{user}}/.config/nemo/desktop-metadata
    # The String to Search
    regexp: "nemo-icon-view-zoom-level="
    # The String to Replace
    line: "nemo-icon-view-zoom-level=2"
    state: present

- name : show desktop icons
  become_user: "{{user}}"
  shell: | 
    gsettings set org.nemo.desktop show-desktop-icons false
    gsettings set org.nemo.desktop show-desktop-icons true

- name: desktop icons
  become_user: "{{user}}"
  shell: | 
    gsettings set org.nemo.desktop computer-icon-visible true
    gsettings set org.nemo.desktop network-icon-visible false
    gsettings set org.nemo.desktop volumes-visible true
    gsettings set org.nemo.desktop home-icon-visible true
    gsettings set org.nemo.desktop show-orphaned-desktop-icons true
    gsettings set org.nemo.desktop trash-icon-visible false

- name: change grid settings
  become_user: "{{user}}"
  shell: | 
    gsettings set org.nemo.desktop use-desktop-grid true
    gsettings set org.nemo.desktop horizontal-grid-adjust 2.0
    gsettings set org.nemo.desktop vertical-grid-adjust 2.0
    gsettings set org.nemo.desktop text-ellipsis-limit 2
    gsettings set org.nemo.desktop desktop-layout 'true::false'

