- name : hide desktop icons
  become_user: "{{user}}"
  command: gsettings set org.nemo.desktop show-desktop-icons false

- name: copy desktop-metadata
  become_user: "{{user}}"
  copy:
    src: files/desktop-metadata
    dest: /home/{{user}}/.config/nemo/desktop-metadata
    mode: 0664

- name : show desktop icons
  become_user: "{{user}}"
  command: gsettings set org.nemo.desktop show-desktop-icons true    

- name: desktop icons
  become_user: "{{user}}"
  shell: | 
    gsettings set org.nemo.desktop computer-icon-visible true
    gsettings set org.nemo.desktop network-icon-visible false
    gsettings set org.nemo.desktop volumes-visible true
    gsettings set org.nemo.desktop home-icon-visible true
    gsettings set org.nemo.desktop show-orphaned-desktop-icons true
    gsettings set org.nemo.desktop trash-icon-visible false

- name: change grid settings
  become_user: "{{user}}"
  shell: | 
    gsettings set org.nemo.desktop use-desktop-grid true
    gsettings set org.nemo.desktop horizontal-grid-adjust 2.0
    gsettings set org.nemo.desktop vertical-grid-adjust 2.0
    gsettings set org.nemo.desktop text-ellipsis-limit 2
    gsettings set org.nemo.desktop desktop-layout 'true::false'

