- name: Install packages
  apt:
    name: 
      - htop
      - neofetch
      - mpv
      - unzip
      - openssh-server
  when: ansible_distribution in ["Ubuntu", "Debian", "Linux Mint"]

- name: Change timezone  
  command: timedatectl set-timezone "Asia/Kolkata" 
