- name: download CBlue Theme
  unarchive:
    src: https://cinnamon-spices.linuxmint.com/files/themes/CBlue.zip
    dest: /home/{{ user }}/.themes
    remote_src: yes

- name: apply theme
  command: gsettings set org.cinnamon.desktop.wm.preferences theme "Mint-Y-Dark"

    
