- name: download CBlue Theme
  unarchive:
    src: "{{ theme_url }}"
    dest: /home/{{ user }}/.themes
    remote_src: yes

- name: change theme
  become_user: "{{user}}"
  command: gsettings set org.cinnamon.theme name "CBlue"


    
