- name: download CBlue Theme
  unarchive:
    src: https://cinnamon-spices.linuxmint.com/files/themes/CBlue.zip
    dest: /home/{{ user }}/.themes
    remote_src: yes

- name: apply theme
  - command:
    with_items:
    - gsettings set org.cinnamon.desktop.wm.preferences theme "Mint-Y-Dark"
    - gsettings set org.cinnamon.desktop.interface gtk-theme "Mint-Y-Dark-Grey"
    - gsettings set org.cinnamon.theme name "CBlue"
    - gsettings set org.cinnamon.desktop.interface icon-theme "Mint-Y-Dark-Grey"
    - gsettings set org.cinnamon.desktop.interface cursor-theme "DMZ-Black"

    
