- name: download CBlue Theme
  unarchive:
    src: {{theme_url}}
    dest: /home/{{ user }}/.themes
    remote_src: yes

- name: change theme
  command: gsettings set org.cinnamon.theme name "CBlue"

- name: change window border
  command: gsettings set org.cinnamon.desktop.wm.preferences theme "Mint-Y-Dark"

- name: change gtk-theme
  command: gsettings set org.cinnamon.desktop.interface gtk-theme "Mint-Y-Dark-Grey"

- name: change icon theme
  command: gsettings set org.cinnamon.desktop.interface icon-theme "Mint-Y-Dark-Grey"

- name: change cursor theme
  command: gsettings set org.cinnamon.desktop.interface cursor-theme "DMZ-Black"
    
