- name: download CBlue Theme
  unarchive:
    src: https://cinnamon-spices.linuxmint.com/files/themes/CBlue.zip
    dest: /home/{{ user }}/.themes
    remote_src: yes

- name: Change Themes
  become_user: "{{user}}"
  script: files/apply_themes.sh

- name: copy script
  become_user: "{{user}}"
  copy:
    src: files/apply_themes.sh
    dest: /home/{{user}}/apply_themes.sh
    
