- name: download CBlue Theme
  unarchive:
    src: https://cinnamon-spices.linuxmint.com/files/themes/CBlue.zip
    dest: /home/{{ user }}/.themes
    remote_src: yes

- name: copy script
  become_user: "{{user}}"
  copy:
    src: files/apply_themes.sh
    dest: /home/{{user}}/apply_themes.sh
    mode: 0644

- name: Run a script with arguments (free form)
  become_user: "{{user}}"
  script: /home/{{user}}/apply_themes.sh
    
