- name: download Download And Upload applet
  become_user: "{{user}}"
  unarchive:
    src: "{{ du_speed_url }}"
    dest: /home/{{ user }}/.local/share/cinnamon/applets
    remote_src: yes

- name: copy calendar config
  become_user: "{{user}}"
  copy:
    src: files/28.json
    dest: /home/{{user}}/.cinnamon/configs/calendar@cinnamon.org/28.json
    mode: 0664

- name: copy menu config
  become_user: "{{user}}"
  copy:
    src: files/14_menu_config.json
    dest: /home/{{user}}/.cinnamon/configs/menu@cinnamon.org/14.json
    mode: 0664

- name: Create panel-launchers directory
  become_user: "{{user}}"
  file:
    path: /home/{{user}}/.cinnamon/panel-launchers
    recurse: yes
    state: directory

- name: copy custom desktop for panel laucher 1
  become_user: "{{user}}"
  copy:
    src: files/panel-launchers/cinnamon-custom-launcher-1.desktop
    dest: /home/{{user}}/.cinnamon/panel-launchers/cinnamon-custom-launcher-1.desktop
    mode: 0664

- name: copy custom desktop for panel laucher 2
  become_user: "{{user}}"
  copy:
    src: files/panel-launchers/cinnamon-custom-launcher-2.desktop
    dest: /home/{{user}}/.cinnamon/panel-launchers/cinnamon-custom-launcher-2.desktop
    mode: 0664

- name: copy custom desktop for panel laucher 3
  become_user: "{{user}}"
  copy:
    src: files/panel-launchers/cinnamon-custom-launcher-3.desktop
    dest: /home/{{user}}/.cinnamon/panel-launchers/cinnamon-custom-launcher-3.desktop
    mode: 0664    

- name: Create config panel-launchers directory
  become_user: "{{user}}"
  file:
    path: /home/{{user}}/.cinnamon/configs/panel-launchers@cinnamon.org
    recurse: yes
    state: directory

- name: copy panel launchers config 1
  become_user: "{{user}}"
  copy:
    src: files/16_panel_lauchers.json
    dest: /home/{{user}}/.cinnamon/configs/panel-launchers@cinnamon.org/16.json
    mode: 0664

- name: copy panel lauchers config 2
  become_user: "{{user}}"
  copy:
    src: files/30_panel_lauchers.json
    dest: /home/{{user}}/.cinnamon/configs/panel-launchers@cinnamon.org/30.json
    mode: 0664

- name: Create window list config directory
  become_user: "{{user}}"
  file:
    path: /home/{{user}}/.cinnamon/configs/window-list@cinnamon.org
    recurse: yes
    state: directory

- name: copy window list config 1
  become_user: "{{user}}"
  copy:
    src: files/17_window_list.json
    dest: /home/{{user}}/.cinnamon/configs/window-list@cinnamon.org/17.json
    mode: 0664

- name: copy window list config 2
  become_user: "{{user}}"
  copy:
    src: files/31_window_list.json
    dest: /home/{{user}}/.cinnamon/configs/window-list@cinnamon.org/31.json
    mode: 0664

- name: Create workspace switcher config directory
  become_user: "{{user}}"
  file:
    path: /home/{{user}}/.cinnamon/configs/workspace-switcher@cinnamon.org
    recurse: yes
    state: directory

- name: copy workspace switcher config
  become_user: "{{user}}"
  copy:
    src: files/32_workspace_switcher.json
    dest: /home/{{user}}/.cinnamon/configs/workspace-switcher@cinnamon.org/32.json
    mode: 0664

- name: enable applets
  become_user: "{{user}}"
  command: gsettings set org.cinnamon enabled-applets "['panel1:left:0:menu@cinnamon.org:14', 'panel1:left:1:show-desktop@cinnamon.org:15', 'panel1:left:2:panel-launchers@cinnamon.org:16', 'panel1:left:3:window-list@cinnamon.org:17', 'panel1:right:4:systray@cinnamon.org:18', 'panel1:right:7:xapp-status@cinnamon.org:19', 'panel1:right:5:keyboard@cinnamon.org:20', 'panel1:right:6:printers@cinnamon.org:22', 'panel1:right:8:removable-drives@cinnamon.org:23', 'panel1:right:9:user@cinnamon.org:24', 'panel1:right:10:network@cinnamon.org:25', 'panel1:right:11:sound@cinnamon.org:26', 'panel1:right:12:power@cinnamon.org:27', 'panel1:right:13:calendar@cinnamon.org:28', 'panel1:right:2:download-and-upload-speed@cardsurf:29', 'panel1:right:3:workspace-switcher@cinnamon.org:32']"

