- name: enable applets
  become_user: "{{user}}"
  command: gsettings set org.cinnamon enabled-applets "['panel1:left:0:menu@cinnamon.org:14', 'panel1:left:1:show-desktop@cinnamon.org:15', 'panel1:left:2:panel-launchers@cinnamon.org:16', 'panel1:left:3:window-list@cinnamon.org:17', 'panel1:right:4:systray@cinnamon.org:18', 'panel1:right:7:xapp-status@cinnamon.org:19', 'panel1:right:5:keyboard@cinnamon.org:20', 'panel1:right:6:printers@cinnamon.org:22', 'panel1:right:8:removable-drives@cinnamon.org:23', 'panel1:right:9:user@cinnamon.org:24', 'panel1:right:10:network@cinnamon.org:25', 'panel1:right:11:sound@cinnamon.org:26', 'panel1:right:12:power@cinnamon.org:27', 'panel1:right:13:calendar@cinnamon.org:28', 'panel1:right:2:download-and-upload-speed@cardsurf:29', 'panel1:right:3:workspace-switcher@cinnamon.org:32']"

- name: panel zone text size
  become_user: "{{user}}"
  command: gsettings set org.cinnamon panel-zone-text-sizes '[{"panelId":1,"left":0,"center":0,"right":0},{"left":0,"center":0,"right":0,"panelId":2}]'

- name: panel symbolic icon size
  become_user: "{{user}}"
  command: gsettings set org.cinnamon panel-zone-symbolic-icon-sizes '[{"panelId":1,"left":28,"center":28,"right":16},{"left":28,"center":28,"right":28,"panelId":2}]'

- name: panel icon size
  become_user: "{{user}}"
  command: gsettings set org.cinnamon panel-zone-icon-sizes '[{"panelId":1,"left":22,"center":0,"right":0},{"left":0,"center":0,"right":0,"panelId":2}]'